import '@/styles/globals.css';
import 'react-toastify/dist/ReactToastify.css';

import SessionProvider from '@/components/SessionProvider';
import { cn } from '@/utils/style';
import type { Metadata } from 'next';
import { getServerSession } from 'next-auth';
import { ToastContainer } from 'react-toastify';

export const metadata: Metadata = {
  title: 'LawLine',
  description: 'Generated by create next app',
  icons: {
    icon: 'images/Favicon192.png',
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body
        className={cn(
          'scrollbar flex overflow-x-hidden',
          'bg-[#F7F7F5]',
          'lg:text-base'
        )}
      >
        <SessionProvider session={session}>
          <main className="flex flex-1 flex-col">
            {children}
            <ToastContainer
              position="top-center"
              autoClose={3000}
              closeOnClick
              pauseOnFocusLoss={true}
              theme="light"
            />
          </main>
        </SessionProvider>
      </body>
    </html>
  );
}
